version: 2

orbs:
  hello:
    executors:
      default:
        docker:
          - image: circleci/ruby:1.4.2
    commands:
      sayhello:
        description: "Hello!"
        parameters:
          to:
            type: string
            default: "Hello World"
        steps:
          - run: echo << parameters.to >>

workflows:
  version: 2
  main:
    jobs:
      - hello/sayhello
      - hello/sayhello:
          to: "Hello CircleCI"

