version: 2

commands:
  sayhello:
    steps:
      - run: echo "Hello World"

jobs:
  hello:
    docker:
      - image: circleci/ruby:2.4.4
    steps:
      - sayhello

workflows:
  version: 2
  main:
    jobs:
      - hello

