version: 2

orbs:
  miyajan:
    executors:
      default:
        docker:
          - image: circleci/ruby:1.4.2
    commands:
      sayhello:
        description: "Hello!"
        parameters:
          to:
            type: string
            default: "World"
        steps:
          - run: echo "Hello << parameters.to >>"
    jobs:
      hello:
        executor: default
        parameters:
          to:
            type: string
            default: "World"
        steps:
          - sayhello:
              to: << parameters.to >>

workflows:
  version: 2
  main:
    jobs:
      - miyajan/hello
      - miyajan/hello:
          to: "Hello CircleCI"

