version: 2

orbs:
  miyajan:
    executors:
      default:
        docker:
          - image: circleci/ruby:1.4.2
    commands:
      sayhello:
        description: "Hello!"
        parameters:
          to:
            type: string
            default: "World"
        steps:
          - run: echo "Hello << parameters.to >>"
    jobs:
      hello:
        executor: default
        parameters:
          to:
            type: string
            default: "World"
        steps:
          - sayhello:
              to: << parameters.to >>

jobs:
  sayhello:
    parameters:
      what:
        default: "World"
        type: string
    docker:
      - image: circleci/ruby:1.4.2
    steps:
      - run: echo "Hello << parameters.what >>"

workflows:
  version: 2
  main:
    jobs:
      - sayhello
      - sayhello:
          to: "Hello CircleCI"

